version: '3.7'
services:
  nodets:
    image: ndknitor/asp-template
    deploy:
      mode: global
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ANOTHER_VARIABLE=another_value
    volumes:
      - ~/logs:/app/logs
# docker stack deploy -c docker-compose.yml asp-template-service
# docker service update --image ndknitor/asp-template asp-template-service
