version: '3.7'
services:
  nodets:
    image: ndknitor/asp-template
    deploy:
      mode: global
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
        
# docker stack deploy -c docker-compose.yml asp-template-service
