apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-template-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asp-template
  template:
    metadata:
      labels:
        app: asp-template
    spec:
      containers:
      - name: asp-template-container
        image: ndknitor/asp-template
        ports:
        - containerPort: 8080
