apiVersion: v1
kind: Service
metadata:
  name: asp-template-service
spec:
  selector:
    app: asp-template
  ports:
    - protocol: TCP
      # port: 8080
      # nodePort: 30000
      targetPort: 8080
  type: ClusterIP
