# 3 matsers, 3 replicas
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-cluster
spec:
  serviceName: redis
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:  
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - worker-3
                - worker-2
                - worker-1
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          command:
            - redis-server
            - "--cluster-enabled"
            - "yes"
            - "--appendonly"
            - "yes"
            - "--port"
            - "6379"
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-cluster
spec:
  clusterIP: None
  ports:
    - port: 6379
  selector:
    app: redis
